### ISSUE TITLE
Modal windows not showing in some case

### ISSUE THREAD

**Issue by Tuttu** [kylefox/jquery-modal#134] opened 2015-11-18 20:14 UTC
Hey there !

First of all, I'm really sorry for this kind of generic title but I have no idea how to call this properly. 

In some case, the modal window won't show up when called with Ajax. 
For example, if the content of my modal window is generated by a PHP function and that I display my text code outside of HTML tag, then the modal window won't appear. For example, if I use a var_dump() PHP function in my code (For debugging purpose) before I write any piece of HTML, this is not good at all. But the same thing happen if a mysql query throw an error for example.
So this piece of code will make the modal window not appearing : 

    <?php
	function Myfunction($ID)
	{
		$myVariable = AnotherFunction($ID);	
		var_dump($myVariable);

		// Some more PHP code here

		?>
		<div>
			<!-- All my HTML code goes here.
		</div>
		<?php
	}
    ?>

But this piece of code will work and the modal window will be shown : 

    <?php
	function Myfunction($ID)
	{
		$myVariable = AnotherFunction($ID);			

		// Some more PHP code here

		?>
		<div>
			<?php var_dump($myVariable); ?>
			<!-- All my HTML code goes here.
		</div>
		<?php
	}
    ?>

I don't know whether this is an intended behavior or not and I'm here to get the answer to this question.
If this is intended rather than some kind of bug, what kind of workaround would you recommend ?

**Comment by kylefox** [comment] 2016-09-11 20:25
To be honest I'm not entirely sure what the problem is or what a solution might be — sorry :(

Closing because this doesn't appear to a problem with the jquery-modal plugin itself.

**Closed by kylefox** 2016-09-11 20:25 UTC

**Comment by Tuttu** [comment] 2016-09-12 05:25
No problem at all. :)
