### ISSUE TITLE
Javascript Redirect within Modal Fails

### ISSUE THREAD

**Issue by wwwmaster1** [kylefox/jquery-modal#236] opened 2018-10-16 19:07 UTC
I am loading modal windows via ajax. I want to make sure the content within my modal windows are not loaded independently (directly), and if that is attempted, I want them redirected to the page that loads the modal. The redirect works great on the direct link, but for some reason, the javascript prevents the modal window from displaying (the ajax calls are fine). I put this inside my html page that will be loaded into the modal...

<script>if (!(window.jQuery)){window.location.href='/';}</script>

Here is the test case (only the state of Texas does not include a redirect, so it works). The other states do not work properly. While the data is loaded, the DIV does not take on the correct ID and styles (jquery-modal blocker current).

http://live.bressler.com/?p=14754

FYI, I've tried placing the script inside and outside of `<DIV class="modal">.` Neither works.

**Comment by kylefox** [comment] 2018-10-16 19:12
This is a duplicate of https://github.com/kylefox/jquery-modal/issues/234 — do not repost the same issue.

This does not appear to be a bug related to the library itself, but rather an implementation issue. Please keep GitHub Issues related to bug reports and feature/improvement requests.

Your best course of action is to post your question to [StackOverflow](https://stackoverflow.com/search?q=jquery-modal) and tag it with `jquery-modal`.

**Closed by kylefox** 2018-10-16 19:12 UTC
