### ISSUE TITLE
Disable the body click to close the modal?

### ISSUE THREAD

**Issue by mtbluedog** [kylefox/jquery-modal#273] opened 2020-05-03 22:03 UTC
This isn't an issue at all, more of a request for help. Is it possible to call jquery modal so that the entire body of the page is not clickable to dismiss the modal. In other words, is it possible to force the user to click the close "X" in the modal and not be able to click anywhere in the body?

**Comment by muzammalrahim** [comment] 2020-05-05 18:43
Duplicate of #257 
Disabled the closing of form with Escape button, and clicking outside form. 

  $('#uploadProgressModal').modal({
            escapeClose: false,
            clickClose: false,
        });

**Comment by mtbluedog** [comment] 2020-05-07 14:58
Ah, I missed that; thanks!

**Closed** 2020-05-07 14:58 UTC
