### ISSUE TITLE
Please release your new code

### ISSUE THREAD

**Issue by Hazarapet** [kylefox/jquery-modal#114] opened 2015-07-13 18:31 UTC
Please release your new code,because in v 0.5.2 there is not any fade option

**Comment by denis-sokolov** [comment] 2015-07-15 11:29
This is probably a duplicate of #105.

**Comment by Hazarapet** [comment] 2015-07-15 12:58
I didn't see it

**Comment by denis-sokolov** [comment] 2015-07-15 13:45
I know, that's why I helpfully provided a link. If that issue seems suitable enough for your needs, you may close this one.

**Comment by kylefox** [comment] 2015-07-15 15:29
Done, should be available: `bower info jquery-modal#0.5.5` will display the package.

**Closed by kylefox** 2015-07-15 15:29 UTC
