### ISSUE TITLE
Unable to modify modal default options

### ISSUE THREAD

**Issue by groschatchauve** [kylefox/jquery-modal#218] opened 2017-11-15 14:53 UTC
I want to set closeExisting to false by default but I get an error.

Here is my code :

`
$('document').ready(function() {
	$.modal.defaults = {
		closeExisting: false,  
		escapeClose: true,    
		clickClose: true, 
		closeText: 'Close',   
		closeClass: '',       
		showClose: true,  
		modalClass: "modal",   
		blockerClass: "modal",
		spinnerHtml: '<div class="rect1"></div><div class="rect2"></div><div class="rect3"></div><div class="rect4"></div>',
		showSpinner: true, 
		fadeDuration: null,
		fadeDelay: 1.0   
	};
});
`

Here is the error :

> jQuery.Deferred exception: Cannot set property 'defaults' of undefined TypeError: Cannot set property 'defaults' of undefined

When I try to use modal function I have this error ;

> $(...).modal is not a function

For the moment, to solve my problem, I fork the js file and replace default closeExisting value by !!0 instead of !0. But If someone can provide a true solution, I will enjoy it.

**Comment by walialu** [comment] 2017-11-15 17:28
Not reproducable. If you can't supply more information, I will close this issue.

See [example](https://pwny.walialu.com/#!/?s=html&c=0&l=1&t=5d000000024103000000000000001e1cc86755bb63d868551718ad8cbca68403eba4557da171d314b923a229b008d46d32ec5507c568b5bdd71079b42162dd6e56ea951b6e6f547f7f1c74ab968cb6cca3ba6d053da834949ea39a43451a5f189cd28f3140db6515f8640054bd035ed59f50b869347ee57e07dd9ea654206b7d2846325996c9e4ae851be5eba597560c6777cdf94cc3617b50fd7bc7072c784f4cb61255435a5e047d5383aeee3d8d1f47db3c2e252a979b2d6230e8710767bf8535dc8a477893daa95b429375fe21a9a5b92221bcb51348cbd03d5591e4bea38e3ac3286920dbcd6db1882900faf1c870e70d36afb80ee7d73b0d22ece45e7fd40c61126ee6b1f33ff4b65061aa5ec9f8a91fac51f28599ac8689f60c8a82c3f8a1bf01c4b60ce8f04927cab320ebc1228f257cd3aa0d2e461ac0d14f90f35ef733173197bcd124070690d461b81eb35a5cb6505d2649254a23e9623db4b0bdadde5ffe5a2563f5d33a3b87eed36ca1416d9ab017fe364e17) (Hamburger Menu -> Run) or this code:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
<script>
  $(document).ready(()=>{
    alert(JSON.stringify($.modal.defaults));
  });
  $.modal.defaults = {
    closeExisting:false,
    escapeClose:true,
    clickClose:true,
    closeText:'Close',
    closeClass:'',
    showClose:true,
    modalClass:"modal",
    blockerClass:"modal",
    spinnerHtml:'<div class="rect1"></div><div class="rect2"></div><div class="rect3"></div><div class="rect4"></div>',
    showSpinner:true,
    fadeDuration:null,
    fadeDelay:1.0
  };
  alert(JSON.stringify($.modal.defaults));
</script>
```

**Comment by kylefox** [comment] 2017-11-15 17:35
This very likely happening because the modal plugin hasn't loaded yet when your code is running.

Make sure your scripts are loading in the correct order:

1. jQuery
2. jQuery Modal (this library)
3. Your code that uses jQuery Modal

It's also recommended to wrap your own code inside a `$(function() { });`. For example:

```html
<!-- 1. Load jQuery -->
<script src="/scripts/jquery.min.js"></script>

<!-- 2. Load jQuery Modal -->
<script src="/scripts/jquery.modal.min.js"></script>

<!-- 3. Your scripts -->
<script>
$(function() {
  // Modify $.modal.defaults here.
});
</script>
```

> If you can't supply more information, I will close this issue.

@walialu I'm going to take this a step further and close the issue 😉 but re-open if more information can be provided.

@groschatchauve Please provide a link to a publicly-accessible page that reproduces and demonstrates the problem we can investigate further.

**Closed by kylefox** 2017-11-15 17:35 UTC
Labels: Implementation Issue
